language: generic

sudo: required

services:
    - docker

env:
    global:
        - DOCKER_IMAGE=webplates/locust

matrix:
    include:
        # 0.8
        - env: VERSION=0.8.1 DOCKER_TAG=latest
        - env: VERSION=0.8.1 DOCKER_TAG=0.8.1
        - env: VERSION=0.8.1 DOCKER_TAG=0.8
        - env: VERSION=0.8.1 DOCKER_TAG=0

script: ./build.sh

deploy:
    provider: script
    script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && docker push $DOCKER_IMAGE:$DOCKER_TAG && docker push $DOCKER_IMAGE:$DOCKER_TAG-onbuild
    on:
        branch: master
