ARG PARENT_VERSION

FROM webplates/locust:${PARENT_VERSION}

RUN mkdir -p /pip

ONBUILD COPY requirements.txt /pip

ONBUILD RUN set -xe \
            && apk add --no-cache build-base \
            && pip install -r /pip/requirements.txt \
            && apk del build-base
