language: generic

sudo: required

services:
    - docker

env:
    global:
        - DOCKER_IMAGE=webplates/beanstalkd

matrix:
    include:
        # 1.10
        - env: VERSION=1.10 DOCKER_TAG=latest DOCKERFILE=Dockerfile
        - env: VERSION=1.10 DOCKER_TAG=1.10 DOCKERFILE=Dockerfile
        - env: VERSION=1.10 DOCKER_TAG=1 DOCKERFILE=Dockerfile
        - env: VERSION=1.10 DOCKER_TAG=latest-alpine DOCKERFILE=Dockerfile-alpine
        - env: VERSION=1.10 DOCKER_TAG=1.10-alpine DOCKERFILE=Dockerfile-alpine
        - env: VERSION=1.10 DOCKER_TAG=1-alpine DOCKERFILE=Dockerfile-alpine

        # 1.9
        - env: VERSION=1.9 DOCKER_TAG=1.9 DOCKERFILE=Dockerfile
        - env: VERSION=1.9 DOCKER_TAG=1.9-alpine DOCKERFILE=Dockerfile-alpine

        # 1.8
        - env: VERSION=1.8 DOCKER_TAG=1.8 DOCKERFILE=Dockerfile
        - env: VERSION=1.8 DOCKER_TAG=1.8-alpine DOCKERFILE=Dockerfile-alpine

script: ./build.sh

deploy:
    provider: script
    script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && docker push $DOCKER_IMAGE:$DOCKER_TAG
    on:
        branch: master
