FROM alpine:3.7

RUN set -x \
    && addgroup -S beanstalk \
    && adduser -D -S -G beanstalk beanstalk

ARG BEANSTALK_VERSION

RUN if [[ -z "$BEANSTALK_VERSION" ]]; then echo "BEANSTALK_VERSION argument MUST be set" && exit 1; fi

RUN set -xe \
    && apk add --no-cache bash \
    && apk add --no-cache --virtual .build-deps \
        gcc \
        curl \
        musl-dev \
        make \
        tar \
    \
    && mkdir -p /usr/src \
    && cd /usr/src \
    && curl -fSL "https://github.com/kr/beanstalkd/archive/v${BEANSTALK_VERSION}.tar.gz" -o beanstalk.tar.gz \
    && mkdir /usr/src/beanstalk \
    && tar -xzf /usr/src/beanstalk.tar.gz -C "/usr/src/beanstalk" --strip-components=1 \
    && cd /usr/src/beanstalk \
    && sed -i 's/sys\/fcntl.h/fcntl.h/g' sd-daemon.c \
    && make \
    && cp beanstalkd /usr/bin/beanstalkd \
    && cd \
    && rm -r /usr/src/beanstalk \
    && apk del .build-deps

COPY entrypoint.sh /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]
EXPOSE 11300
CMD ["beanstalkd"]
