language: generic

sudo: required

services:
    - docker

env:
    global:
        - DOCKER_IMAGE=webplates/readthedocs
        - DOCKER_TAG=latest

script: ./build.sh

deploy:
    provider: script
    script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && docker push $DOCKER_IMAGE:$DOCKER_TAG
    on:
        branch: master
