language: generic

sudo: required

services:
    - docker

env:
    global:
        - DOCKER_IMAGE=webplates/stunnel

matrix:
    include:
        # 5.43
        - env: VERSION=5.43-r0 DOCKER_TAG=latest
        - env: VERSION=5.43-r0 DOCKER_TAG=5.43
        - env: VERSION=5.43-r0 DOCKER_TAG=5

script: ./build.sh

deploy:
    provider: script
    script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && docker push $DOCKER_IMAGE:$DOCKER_TAG
    on:
        branch: master
