language: generic

sudo: required

services:
    - docker

env:
    global:
        - DOCKER_IMAGE=webplates/protolock

matrix:
    include:
        # 0.6
        - env: VERSION=0.6.0 BUILD=20180621T191216Z DOCKER_TAG=latest
        - env: VERSION=0.6.0 BUILD=20180621T191216Z DOCKER_TAG=0.6.0
        - env: VERSION=0.6.0 BUILD=20180621T191216Z DOCKER_TAG=0.6

script: ./build.sh

deploy:
    provider: script
    script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && docker push $DOCKER_IMAGE:$DOCKER_TAG
    on:
        branch: master
