language: generic

sudo: required

services:
    - docker

env:
    global:
        - DOCKER_IMAGE=webplates/grpc-cli

matrix:
    include:
        # 1.10
        - env: VERSION=1.10.0 DOCKER_TAG=latest
        - env: VERSION=1.10.0 DOCKER_TAG=1.10.0
        - env: VERSION=1.10.0 DOCKER_TAG=1.10
        - env: VERSION=1.10.0 DOCKER_TAG=1

        # 1.9
        - env: VERSION=1.9.1 DOCKER_TAG=1.9.1
        - env: VERSION=1.9.1 DOCKER_TAG=1.9

        # 1.8
        - env: VERSION=1.8.6 DOCKER_TAG=1.8.6
        - env: VERSION=1.8.6 DOCKER_TAG=1.8

        # 1.7
        - env: VERSION=1.7.3 DOCKER_TAG=1.7.3
        - env: VERSION=1.7.3 DOCKER_TAG=1.7

        # 1.6
        - env: VERSION=1.6.7 DOCKER_TAG=1.6.7
        - env: VERSION=1.6.7 DOCKER_TAG=1.6

script: ./build.sh

deploy:
    provider: script
    script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && docker push $DOCKER_IMAGE:$DOCKER_TAG
    on:
        branch: master
